export const ESTADO_MEXICO_MUNICIPALITIES = [
    { id: 1, name: "ACAMBAY DE RUIZ CASTAÑEDA" },
    { id: 2, name: "ACOLMAN" },
    { id: 3, name: "ACULCO" },
    { id: 4, name: "ALMOLOYA DE ALQUISIRAS" },
    { id: 5, name: "ALMOLOYA DE JUÁREZ" },
    { id: 6, name: "ALMOLOYA DEL RÍO" },
    { id: 7, name: "AMANALCO" },
    { id: 8, name: "AMATEPEC" },
    { id: 9, name: "AMECAMECA" },
    { id: 10, name: "APAXCO" },
    { id: 11, name: "ATENCO" },
    { id: 12, name: "ATIZAPÁN" },
    { id: 13, name: "ATIZAPÁN DE ZARAGOZA" },
    { id: 14, name: "ATLACOMULCO" },
    { id: 15, name: "ATLAUTLA" },
    { id: 16, name: "AXAPUSCO" },
    { id: 17, name: "AYAPANGO" },
    { id: 18, name: "CALIMAYA" },
    { id: 19, name: "CAPULHUAC" },
    { id: 20, name: "COACALCO DE BERRIOZÁBAL" },
    { id: 21, name: "COATEPEC HARINAS" },
    { id: 22, name: "COCOTITLÁN" },
    { id: 23, name: "COYOTEPEC" },
    { id: 24, name: "CUAUTITLÁN" },
    { id: 25, name: "CUAUTITLÁN IZCALLI" },
    { id: 26, name: "CHALCO" },
    { id: 27, name: "CHAPA DE MOTA" },
    { id: 28, name: "CHAPULTEPEC" },
    { id: 29, name: "CHIAUTLA" },
    { id: 30, name: "CHICOLOAPAN" },
    { id: 31, name: "CHICONCUAC" },
    { id: 32, name: "CHIMALHUACÁN" },
    { id: 33, name: "DONATO GUERRA" },
    { id: 34, name: "ECATEPEC DE MORELOS" },
    { id: 35, name: "ECATZINGO" },
    { id: 36, name: "HUEHUETOCA" },
    { id: 37, name: "HUEYPOXTLA" },
    { id: 38, name: "HUIXQUILUCAN" },
    { id: 39, name: "ISIDRO FABELA" },
    { id: 40, name: "IXTAPALUCA" },
    { id: 41, name: "IXTAPAN DE LA SAL" },
    { id: 42, name: "IXTAPAN DEL ORO" },
    { id: 43, name: "IXTLAHUACA" },
    { id: 44, name: "XALATLACO" },
    { id: 45, name: "JALTENCO" },
    { id: 46, name: "JILOTEPEC" },
    { id: 47, name: "JILOTZINGO" },
    { id: 48, name: "JIQUIPILCO" },
    { id: 49, name: "JOCOTITLÁN" },
    { id: 50, name: "JOQUICINGO" },
    { id: 51, name: "JUCHITEPEC" },
    { id: 52, name: "LERMA" },
    { id: 53, name: "MALINALCO" },
    { id: 54, name: "MELCHOR OCAMPO" },
    { id: 55, name: "METEPEC" },
    { id: 56, name: "MEXICALTZINGO" },
    { id: 57, name: "MORELOS" },
    { id: 58, name: "NAUCALPAN DE JUÁREZ" },
    { id: 59, name: "NEXTLALPAN" },
    { id: 60, name: "NEZAHUALCÓYOTL" },
    { id: 61, name: "NICOLÁS ROMERO" },
    { id: 62, name: "NOPALTEPEC" },
    { id: 63, name: "OCOYOACAC" },
    { id: 64, name: "OCUILAN" },
    { id: 65, name: "EL ORO" },
    { id: 66, name: "OTUMBA" },
    { id: 67, name: "OTZOLOAPAN" },
    { id: 68, name: "OTZOLOTEPEC" },
    { id: 69, name: "OZUMBA" },
    { id: 70, name: "PAPALOTLA" },
    { id: 71, name: "LA PAZ" },
    { id: 72, name: "POLOTITLÁN" },
    { id: 73, name: "RAYÓN" },
    { id: 74, name: "SAN ANTONIO LA ISLA" },
    { id: 75, name: "SAN FELIPE DEL PROGRESO" },
    { id: 76, name: "SAN MARTÍN DE LAS PIRÁMIDES" },
    { id: 77, name: "SAN MATEO ATENCO" },
    { id: 78, name: "SAN SIMÓN DE GUERRERO" },
    { id: 79, name: "SANTO TOMÁS" },
    { id: 80, name: "SOYANIQUILPAN DE JUÁREZ" },
    { id: 81, name: "SULTEPEC" },
    { id: 82, name: "TECÁMAC" },
    { id: 83, name: "TEJUPILCO" },
    { id: 84, name: "TEMAMATLA" },
    { id: 85, name: "TEMASCALAPA" },
    { id: 86, name: "TEMASCALCINGO" },
    { id: 87, name: "TEMASCALTEPEC" },
    { id: 88, name: "TEMOAYA" },
    { id: 89, name: "TENANCINGO" },
    { id: 90, name: "TENANGO DEL AIRE" },
    { id: 91, name: "TENANGO DEL VALLE" },
    { id: 92, name: "TEOLOYUCAN" },
    { id: 93, name: "TEOTIHUACÁN" },
    { id: 94, name: "TEPETLAOXTOC" },
    { id: 95, name: "TEPETLIXPA" },
    { id: 96, name: "TEPOTZOTLÁN" },
    { id: 97, name: "TEQUIXQUIAC" },
    { id: 98, name: "TEXCALTITLÁN" },
    { id: 99, name: "TEXCALYACAC" },
    { id: 100, name: "TEXCOCO" },
    { id: 101, name: "TEZOYUCA" },
    { id: 102, name: "TIANGUISTENCO" },
    { id: 103, name: "TIMILPAN" },
    { id: 104, name: "TLALMANALCO" },
    { id: 105, name: "TLALNEPANTLA DE BAZ" },
    { id: 106, name: "TLATLAYA" },
    { id: 107, name: "TOLUCA" },
    { id: 108, name: "TONATICO" },
    { id: 109, name: "TULTEPEC" },
    { id: 110, name: "TULTITLÁN" },
    { id: 111, name: "VALLE DE BRAVO" },
    { id: 112, name: "VILLA DE ALLENDE" },
    { id: 113, name: "VILLA DEL CARBÓN" },
    { id: 114, name: "VILLA GUERRERO" },
    { id: 115, name: "VILLA VICTORIA" },
    { id: 116, name: "XONACATLÁN" },
    { id: 117, name: "ZACAZONAPAN" },
    { id: 118, name: "ZACUALPAN" },
    { id: 119, name: "ZINACANTEPEC" },
    { id: 120, name: "ZUMPAHUACÁN" },
    { id: 121, name: "ZUMPANGO" },
    { id: 122, name: "VALLE DE CHALCO SOLIDARIDAD" },
    { id: 123, name: "LUVIANOS" },
    { id: 124, name: "SAN JOSÉ DEL RINCÓN" },
    { id: 125, name: "TONANITLA" }
];
